
package org.vk.test.ws.types;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UtilTest", targetNamespace = "http://www.example.org/UtilTest", wsdlLocation = "file:/Users/viko/Documents/workspace/web-service-test/src/main/resources/UtilTest.wsdl")
public class UtilTest
    extends Service
{

    private final static URL UTILTEST_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.vk.test.ws.types.UtilTest.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.vk.test.ws.types.UtilTest.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/viko/Documents/workspace/web-service-test/src/main/resources/UtilTest.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/viko/Documents/workspace/web-service-test/src/main/resources/UtilTest.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        UTILTEST_WSDL_LOCATION = url;
    }

    public UtilTest(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilTest() {
        super(UTILTEST_WSDL_LOCATION, new QName("http://www.example.org/UtilTest", "UtilTest"));
    }

    /**
     * 
     * @return
     *     returns UtilTestWS
     */
    @WebEndpoint(name = "UtilTestSOAP")
    public UtilTestWS getUtilTestSOAP() {
        return super.getPort(new QName("http://www.example.org/UtilTest", "UtilTestSOAP"), UtilTestWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilTestWS
     */
    @WebEndpoint(name = "UtilTestSOAP")
    public UtilTestWS getUtilTestSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/UtilTest", "UtilTestSOAP"), UtilTestWS.class, features);
    }

}
