
package org.vk.test.ws.types;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UtilTestPort", targetNamespace = "http://www.example.org/UtilTest")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtilTestWS {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.vk.test.ws.types.WebServiceTestResponse
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/UtilTest/NewOperation")
    @WebResult(name = "webServiceTestResponse", targetNamespace = "http://www.example.org/UtilTest", partName = "parameters")
    public WebServiceTestResponse newOperation(
        @WebParam(name = "webServiceTestRequest", targetNamespace = "http://www.example.org/UtilTest", partName = "parameters")
        WebServiceTestRequest parameters);

}
