<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.example.org/UtilTest" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="UtilTest"
	xmlns:jaxws="http://java.sun.com/xml/ns/jaxws" targetNamespace="http://www.example.org/UtilTest">

	<jaxws:bindings>
		<jaxws:package name="org.vk.test.ws.types" />
	</jaxws:bindings>

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.example.org/UtilTest"
				schemaLocation="UtilTest.xsd" />
		</xsd:schema>
	</wsdl:types>


	<wsdl:message name="webServiceTestRequest">
		<wsdl:part element="tns:webServiceTestRequest" name="parameters" />
	</wsdl:message>
	
	<wsdl:message name="webServiceTestResponse">
		<wsdl:part element="tns:webServiceTestResponse" name="parameters" />
	</wsdl:message>
	
	<wsdl:portType name="UtilTestPort">
		<jaxws:bindings>
			<jaxws:class name="UtilTestWS" />
		</jaxws:bindings>
		<wsdl:operation name="NewOperation">
			<wsdl:input message="tns:webServiceTestRequest" />
			<wsdl:output message="tns:webServiceTestResponse" />
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="UtilTestSOAP" type="tns:UtilTestPort">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="NewOperation">
			<soap:operation soapAction="http://www.example.org/UtilTest/NewOperation" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="UtilTest">
		<wsdl:port binding="tns:UtilTestSOAP" name="UtilTestSOAP">
			<soap:address location="http://www.example.org/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
